name: 'airflow_dbt'
version: '1.0.0'

profile: 'dbt_bigquery'

vars:
  'dbt_datetime_zone': 'America/New_York'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  airflow_dbt:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    mart:
      +materialized: table
      +schema: mart
